development:
  adapter: postgresql
  database: inferno_community
  username: postgres
  host: db
  pool: 10
  idle_timeout: 60

production:
  adapter: postgresql
  database: inferno_community
  username: postgres
  host: db
  pool: 10
  idle_timeout: 60

test: &test
  adapter: postgresql
  database: inferno_community
  username: postgres
  host: db
  pool: 10
  idle_timeout: 60
