development:
  adapter: postgresql
  database: inferno_program
  username: postgres
  host: db
  pool: 10
  timeout: 5000

production:
  adapter: postgresql
  database: inferno_program
  username: postgres
  host: db
  pool: 10
  timeout: 5000

test: &test
  adapter: postgresql
  database: inferno_program
  username: postgres
  host: db
  pool: 10
  timeout: 5000
